/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
    "./node_modules/react-tailwindcss-datepicker/dist/index.esm.js",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#003076",
        "on-tertiary": "#003652",
        "primary-dim": "hsl(var(--primary-dim) / <alpha-value>)",
        "error": "hsl(var(--error) / <alpha-value>)",
        "inverse-surface": "#fcf8ff",
        "surface-bright": "#2b2b35",
        "surface-container-highest": "hsl(var(--surface-container-highest) / <alpha-value>)",
        "error-dim": "#d73357",
        "outline-variant": "hsl(var(--outline-variant) / <alpha-value>)",
        "surface-container": "hsl(var(--surface-container) / <alpha-value>)",
        "inverse-on-surface": "#55545c",
        "secondary-fixed": "#c1d1ff",
        "surface-dim": "#0e0e14",
        "on-primary-container": "#280072",
        "tertiary": "hsl(var(--tertiary) / <alpha-value>)",
        "surface-tint": "#b6a0ff",
        "secondary-container": "#0c47a1",
        "on-secondary": "#002053",
        "on-primary-fixed-variant": "#32008a",
        "surface-container-high": "hsl(var(--surface-container-high) / <alpha-value>)",
        "secondary": "hsl(var(--secondary) / <alpha-value>)",
        "inverse-primary": "#6834eb",
        "surface-container-low": "hsl(var(--surface-container-low) / <alpha-value>)",
        "outline": "#76747d",
        "surface": "#0e0e14",
        "error-container": "#a70138",
        "on-secondary-container": "#cad7ff",
        "on-error": "#490013",
        "tertiary-fixed-dim": "#00adfa",
        "on-primary": "#340090",
        "on-secondary-fixed-variant": "#174ca6",
        "background": "hsl(var(--background) / <alpha-value>)",
        "primary-fixed": "#a98fff",
        "tertiary-fixed": "#4cb9ff",
        "primary-container": "#a98fff",
        "on-surface": "hsl(var(--on-surface) / <alpha-value>)",
        "tertiary-container": "#00affe",
        "tertiary-dim": "#00a7f2",
        "on-primary-fixed": "#000000",
        "on-tertiary-fixed-variant": "#003d5c",
        "on-background": "hsl(var(--on-background) / <alpha-value>)",
        "primary": "hsl(var(--primary) / <alpha-value>)",
        "on-tertiary-container": "#002a42",
        "surface-variant": "#25252e",
        "secondary-dim": "#729bfa",
        "secondary-fixed-dim": "#acc3ff",
        "on-tertiary-fixed": "#001a2a",
        "on-error-container": "#ffb2b9",
        "on-surface-variant": "hsl(var(--on-surface-variant) / <alpha-value>)",
        "primary-fixed-dim": "#9c7eff",
        // Keep CSS variables for generic fallbacks
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        '3xl': '1.5rem',
        '4xl': '2rem',
        lg: "1rem",
        md: "calc(1rem - 2px)",
        sm: "calc(1rem - 4px)",
      },
    },
  },
  plugins: [],
}
